# Generated by Django 3.2.12 on 2022-02-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=200)),
                ('PostImage', models.ImageField(upload_to='feedpost/')),
                ('addImage', models.ImageField(null=True, upload_to='feedpost/')),
                ('publisheddate', models.DateTimeField(auto_now_add=True)),
                ('updateddate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('updateddate',),
            },
        ),
    ]
