# Generated by Django 3.2.12 on 2022-02-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedpost',
            options={'ordering': ('-publisheddate',)},
        ),
        migrations.RenameField(
            model_name='feedpost',
            old_name='addImage',
            new_name='addImage1',
        ),
        migrations.AddField(
            model_name='feedpost',
            name='addImage2',
            field=models.ImageField(null=True, upload_to='feedpost/'),
        ),
        migrations.AddField(
            model_name='feedpost',
            name='addImage3',
            field=models.ImageField(null=True, upload_to='feedpost/'),
        ),
    ]
