# Generated by Django 3.2.12 on 2022-02-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20220220_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpost',
            name='addImage1',
            field=models.ImageField(blank=True, null=True, upload_to='feedpost/'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='addImage2',
            field=models.ImageField(blank=True, null=True, upload_to='feedpost/'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='addImage3',
            field=models.ImageField(blank=True, null=True, upload_to='feedpost/'),
        ),
    ]
