# Generated by Django 3.2.12 on 2022-03-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_auto_20220222_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedpost',
            name='addImage1',
        ),
        migrations.RemoveField(
            model_name='feedpost',
            name='addImage2',
        ),
        migrations.RemoveField(
            model_name='feedpost',
            name='addImage3',
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='publisheddate',
            field=models.DateTimeField(default='02.03.22 22:00:42'),
        ),
    ]
