# Generated by Django 3.2.12 on 2022-03-11 20:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_alter_feedpost_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpost',
            name='body',
            field=ckeditor.fields.RichTextField(max_length=1000),
        ),
    ]
