# Generated by Django 3.2.12 on 2022-02-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signals',
            name='Buy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signals',
            name='PostImage',
            field=models.ImageField(blank=True, null=True, upload_to='signals/feedpost/'),
        ),
        migrations.AddField(
            model_name='signals',
            name='body',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='signals',
            name='SL',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signals',
            name='TP',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
