# Generated by Django 3.2.12 on 2022-02-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_auto_20220220_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='signals',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
