# Generated by Django 3.2.12 on 2022-03-11 20:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0003_signals_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signals',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, max_length=200, null=True),
        ),
    ]
