# Generated by Django 3.2.12 on 2022-03-14 18:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0004_alter_signals_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signals',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
    ]
